export const defaultSetup = {
  machine: "",
  grinder: "",
  hasBuiltInGrinder: false,
  basket: "18 g precision basket",
  portafilter: "Bottomless",
  puckScreen: true,
  waterTemperature: 93,
};

export const defaultBeans = [
  {
    id: "bean-ethiopia-guji",
    name: "Worka Sakaro",
    roaster: "North Star Coffee",
    origin: "Guji, Ethiopia",
    roastLevel: "Light",
    roastDate: "2026-06-18",
    flavorNotes: "Peach, jasmine, honey",
    drinkingStyle: "Espresso",
    active: true,
    recipe: {
      dose: 18,
      yield: 40,
      extractionTime: 29,
      waterTemperature: 94,
      grindSize: "18",
      grinderTime: 10.5,
      basket: "18 g precision basket",
      portafilter: "Bottomless",
      puckScreen: true,
    },
  },
  {
    id: "bean-brazil-serra",
    name: "Serra Negra",
    roaster: "Assembly Coffee",
    origin: "Minas Gerais, Brazil",
    roastLevel: "Medium",
    roastDate: "2026-06-14",
    flavorNotes: "Praline, cacao, red apple",
    drinkingStyle: "Flat white",
    active: false,
    recipe: {
      dose: 18,
      yield: 36,
      extractionTime: 28,
      waterTemperature: 92,
      grindSize: "20",
      grinderTime: 10,
      basket: "18 g precision basket",
      portafilter: "Bottomless",
      puckScreen: true,
    },
  },
];

export const defaultShots = [
  {
    id: "shot-sample",
    beanId: "bean-ethiopia-guji",
    createdAt: "2026-06-25T06:48:00.000Z",
    dose: 18,
    yield: 41,
    extractionTime: 27,
    waterTemperature: 94,
    grindSize: "18",
    grinderTime: 10.5,
    basket: "18 g precision basket",
    portafilter: "Bottomless",
    puckScreen: true,
    taste: "Balanced",
    flow: "Normal",
    notes: "Sweet and floral. A touch quick at the finish.",
    rating: 4,
    recommendation: {
      action: "Keep the recipe",
      detail: "This shot is balanced with a normal flow. Repeat it before making another change.",
      direction: "repeat",
    },
  },
];
